title: IoTGirlNextDoor
author: Agrippina Mwangi
email: agrippinamwangi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Traveling through Education
# social links
twitter_username: https://twitter.com/grippish
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
